apiVersion: batch/v1
kind: CronJob
metadata:
  name: toopasbo-cronjob-daily
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: toopasbo
            image: registry.k8s.smee.ovh/bryansmee-projects/toopasbo@sha256:d7f8a0dce8430167e3e9a7b0a14af3aad04370d60f6efd3d4b9fd690d8c5a63f
            args: ["-job=daily"]
            env:
              - name: OPENWEATHER_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: OPENWEATHER_API_KEY
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: OPENAI_API_KEY
              - name: TELEGRAM_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: TELEGRAM_BOT_TOKEN
              - name: CLOUDEVENT_TARGET
                value: "http://toopasbo-service:8080"
            resources:
              limits:
                cpu: "0.2"
                memory: "200Mi"
            volumeMounts:
              - name: toopasbo-volume
                mountPath: /persistentdata
          volumes:
            - name: toopasbo-volume
              persistentVolumeClaim:
                claimName: toopasbo-pvc
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: toopasbo-cronjob-weekly
spec:
  schedule: "0 8 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: toopasbo
            image: registry.k8s.smee.ovh/bryansmee-projects/toopasbo@sha256:d7f8a0dce8430167e3e9a7b0a14af3aad04370d60f6efd3d4b9fd690d8c5a63f
            args: ["-job=weekly"]
            env:
              - name: OPENWEATHER_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: OPENWEATHER_API_KEY
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: OPENAI_API_KEY
              - name: TELEGRAM_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: TELEGRAM_BOT_TOKEN
              - name: CLOUDEVENT_TARGET
                value: "http://toopasbo-service:8080"
            resources:
              limits:
                cpu: "0.2"
                memory: "200Mi"
            volumeMounts:
              - name: toopasbo-volume
                mountPath: /persistentdata
          volumes:
            - name: toopasbo-volume
              persistentVolumeClaim:
                claimName: toopasbo-pvc
          restartPolicy: Never