apiVersion: batch/v1
kind: CronJob
metadata:
  name: toopasbo-cronjob
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - name: toopasbo
              image: registry.k8s.smee.ovh/bryansmee/toopasbo@sha256:328e9603076b9d8811b3cc7928f3ea5847f8c872774f8d3b399afcaad664552f
              restartPolicy: never
              args: ["-server=true"]
              env:
                - name: OPENWEATHER_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: toopasbo-secret
                      key: OPENWEATHER_API_KEY
                - name: OPENAI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: toopasbo-secret
                      key: OPENAI_API_KEY
                - name: TELEGRAM_BOT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: toopasbo-secret
                      key: TELEGRAM_BOT_TOKEN
              resources:
                limits:
                  cpu: "0.2"
                  memory: "200Mi"
              volumeMounts:
                - name: chatids-volume
                  mountPath: /app/chat_ids.txt
                  subPath: chat_ids.txt
          volumes:
            - name: chatids-volume
              persistentVolumeClaim:
                claimName: chatids-pvc