apiVersion: batch/v1
kind: CronJob
metadata:
  name: toopasbo-cronjob-daily
spec:
  schedule: "15 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: toopasbo
            image: registry.k8s.smee.ovh/bryansmee-projects/toopasbo@sha256:a66a2935cd1c2668e838ac862cfe852bace22f9e1738e20aa70defe5a7f620f4
            args: ["-job=daily"]
            env:
              - name: OPENWEATHER_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: OPENWEATHER_API_KEY
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: OPENAI_API_KEY
              - name: TELEGRAM_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: TELEGRAM_BOT_TOKEN
              - name: CLOUDEVENT_TARGET
                value: "http://toopasbo-service:8080"
              - name: MIDJOURNEY_API_URL
                value: "http://midjourney-api-service.midjourney-api.svc.cluster.local:3000"
            resources:
              limits:
                cpu: "0.2"
                memory: "200Mi"
            volumeMounts:
              - name: toopasbo-volume
                mountPath: /persistentdata
          volumes:
            - name: toopasbo-volume
              persistentVolumeClaim:
                claimName: toopasbo-pvc
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: toopasbo-cronjob-weekly
spec:
  schedule: "15 7 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: toopasbo
            image: registry.k8s.smee.ovh/bryansmee-projects/toopasbo@sha256:a66a2935cd1c2668e838ac862cfe852bace22f9e1738e20aa70defe5a7f620f4
            args: ["-job=weekly"]
            env:
              - name: OPENWEATHER_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: OPENWEATHER_API_KEY
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: OPENAI_API_KEY
              - name: TELEGRAM_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: toopasbo-secret
                    key: TELEGRAM_BOT_TOKEN
              - name: CLOUDEVENT_TARGET
                value: "http://toopasbo-service:8080"
              - name: MIDJOURNEY_API_URL
                value: "http://midjourney-api-service.midjourney-api.svc.cluster.local:3000"
            resources:
              limits:
                cpu: "0.2"
                memory: "200Mi"
            volumeMounts:
              - name: toopasbo-volume
                mountPath: /persistentdata
          volumes:
            - name: toopasbo-volume
              persistentVolumeClaim:
                claimName: toopasbo-pvc
          restartPolicy: Never