apiVersion: apps/v1
kind: Deployment
metadata:
  name: toopasbo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toopasbo
  template:
    metadata:
      labels:
        app: toopasbo
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: toopasbo
          image: registry.k8s.smee.ovh/bryansmee/toopasbo@sha256:7a4318b40dd6fce39caa7f45e8f96282f06bdbafebd5a48aa933e1690596b536
          args: ["-server"]
          env:
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: toopasbo-secret
                  key: OPENWEATHER_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: toopasbo-secret
                  key: OPENAI_API_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: toopasbo-secret
                  key: TELEGRAM_BOT_TOKEN
          resources:
            limits:
              cpu: "0.2"
              memory: "200Mi"
          volumeMounts:
            - name: chatids-volume
              mountPath: /chat_ids.txt
              subPath: chat_ids.txt
      volumes:
        - name: chatids-volume
          persistentVolumeClaim:
            claimName: chatids-pvc