apiVersion: apps/v1
kind: Deployment
metadata:
  name: toopasbo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: toopasbo
  template:
    metadata:
      labels:
        app: toopasbo
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: toopasbo
          image: registry.k8s.smee.ovh/bryansmee-projects/toopasbo@sha256:408a9a3d2840cc7079ae041a423e53fd895decb044744d8731b0bc10d0db9407
          args: ["-server"]
          env:
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: toopasbo-secret
                  key: OPENWEATHER_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: toopasbo-secret
                  key: OPENAI_API_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: toopasbo-secret
                  key: TELEGRAM_BOT_TOKEN
          resources:
            limits:
              cpu: "0.2"
              memory: "200Mi"
          volumeMounts:
            - name: toopasbo-volume
              mountPath: /persistentdata
      volumes:
        - name: toopasbo-volume
          persistentVolumeClaim:
            claimName: toopasbo-pvc