apiVersion: apps/v1
kind: Deployment
metadata:
  name: toopasbo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: toopasbo
  template:
    metadata:
      labels:
        app: toopasbo
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: toopasbo
          image: ghcr.io/bryansmee-projects/toopasbo@sha256:e05133fd376579d73d06439b69d1c9013be79794600f93443d033806546309e8
          args: ["-server"]
          ports:
            - containerPort: 8080
          env:
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: toopasbo-secret
                  key: OPENWEATHER_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: toopasbo-secret
                  key: OPENAI_API_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: toopasbo-secret
                  key: TELEGRAM_BOT_TOKEN
            - name: CLOUDEVENT_PORT
              value: "8080"
            - name: MIDJOURNEY_API_URL
              value: "http://midjourney-api-service.midjourney-api.svc.cluster.local:3000"
          resources:
            limits:
              cpu: "0.2"
              memory: "200Mi"
          volumeMounts:
            - name: toopasbo-volume
              mountPath: /persistentdata
      volumes:
        - name: toopasbo-volume
          persistentVolumeClaim:
            claimName: toopasbo-pvc