name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  issues: write

jobs:

  build:
    runs-on: arc-runner-set
    steps:
    - name: Install git
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends git

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry: registry.k8s.smee.ovh
        username: github-bot
        password: ${{ secrets.registry_password }}
    
    - name: Docker Metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
          images: registry.k8s.smee.ovh/${{ github.repository }}
          tags: |
            type=sha
            latest

    - name: Build and push
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Compute image name
      id: image_name
      run: |
        # Get github.repository on lowercase
        REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "IMAGE_NAME=registry.k8s.smee.ovh/$REPO@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
    
    - name: Update Kubernetes deployment image
      run: |
        sed -i 's|image:.*|image: ${{ steps.image_name.outputs.image_name }}|' argocd/deployment.yaml
        # sed -i 's|image:.*|image: ${{ steps.image_name.outputs.image_name }}|' argocd/cronjob.yaml
      shell: bash

    - name: Commit and push updated manifests
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add argocd/deployment.yaml
        git commit -m "Update deployment image to new version"
        git push
