name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry: registry.k8s.smee.ovh
        username: github-bot
        password: ${{ secrets.registry_password }}

    
    - name: Docker Metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
          images: registry.k8s.smee.ovh/${{ github.repository }}
          tags: |
            type=sha
            latest


    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
